export const email = "#customer-email-fieldset #customer-email"
export const firstname = "input[name=\"firstname\"]"
export const lastname = "input[name=\"lastname\"]"
export const company = "input[name=\"company\"]"
export const street_address = "input[name=\"street[0]\"]"
export const country = "input[name=\"country_id\"]"
export const state = "select[name=\"region_id\"]"
export const city = "input[name=\"city\"]"
export const zip = "input[name=\"postcode\"]"
export const phone = "input[name=\"telephone\"]"
